### PR TITLE
Remove non-sensical input to make computation faster

### PR DESCRIPTION
**Pull request by Inventitech**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by Inventitech** [comment]
Thank you :)

**Comment by gaborcsardi** [comment]
Hmmm. Looks like this breaks some test cases: https://travis-ci.org/gaborcsardi/parsedate/jobs/206722572 

Do you mind taking a look?

**Comment by Inventitech** [comment]
See #19

**Pull request merged**
